### ISSUE TITLE
A bit of errors

### ISSUE THREAD

**Issue by Soarex16** [TwistedTwigleg/Godot_FPS_Tutorial#1]
## **1.** invalid get index 'UNARMED' (on base 'Dictionary')
error when pressing R without ammo

## **2.**  dependencies error
res://Sonniss_GDC_Game_Audio/Gamemaster_audio_gun_sound_pack/gun_revolver_pistol_shot_04_edited.ogg

## **3.** Poor performance on fairly powerful devices
40 fps but very strong freezes

## **4.** In the test scene, the cubes after going into a steady state do not move the player until they are shot (can be interacted after shot)
Disable "Can sleep" in cubes RigidBodies

## **5.** the change in gravity during a sprint affects the height of the jump

**Comment by TwistedTwigleg** [comment]
Thanks Soarex16! I'll look into fixing these soon!

EDIT
_____

Number 3 is likely due to the use of GI_probes. Is performance poor in `Testing_Area.tscn` as well? I'll check later once I have the chance. My suspicion is the GI_probes in `Test_Level.tscn` are causing the performance drops.

Number 5 is on purpose. I've found that adding a little extra height while sprinting makes it 'feel' faster. Not sure if it is a good addition though. What do you think?

**Comment by Soarex16** [comment]
disabling GI_probes does not help

Regarding acceleration - no, this is not the best idea, because you can lock the shift only in order to jump higher

**Comment by TwistedTwigleg** [comment]
Hmm... I'll see if I can nail down the performance issue.
(and I'll remove the extra jump height when sprinting :+1: )

EDIT: Seems the performance issue is related to idle time. I'm not sure why it's causing performance drops though...

**Comment by TwistedTwigleg** [comment]
Fixed all but number 3 in the most recent commit: be35009c8d5d1b750360b85b23a306b418a84ae0
(probably should have made a pull request instead of directly pushing the changes... Oh well!)

I tried fixing the performance drops in `Test_level.tscn` but I couldn't find a solution. I think the problem is due to how many static collision shapes there are, but I have not been able to confirm this. I will open a new issue for this matter.

Thanks!
