### ISSUE TITLE
The .godot file doesn't open when I import it to Godot

### ISSUE THREAD

**Issue by ghost** [TwistedTwigleg/Godot_FPS_Tutorial#23]
In Godot 3.0.2 it doesn't open when I try to open it in Godot. This is the only file that does this. When I click 'Edit', it tries to open the editor and crashes, going back to the project select page. Any idea why this is happening?

I also tried it on Godot 3.0.5 and it didn't work on that either. I tried it on two different computers, both Mac Minis. Didn't want to open.

Sory if there are any mistakes in this, I'm typing this with an iPod.

TIA,
Zeph

**Comment by TwistedTwigleg** [comment]
Hey Zeph!

The reason you cannot open the project with Godot 3.0.2 or 3.0.5 is because the project here on Github was updated for Godot 3.1/master. You can download the project for Godot 3.0 by going to the [documentation for Godot 3.0](
http://docs.godotengine.org/en/3.0/tutorials/3d/fps_tutorial/index.htm) and then download the completed project from part 6. The Godot 3.0 project is missing a few bug fixes, but the majority of the code is the same as the version here on Github.

If you want to download/use the project here on Github, I’d recommend either building Godot from source, or downloading a nightly build (like one from [here](
https://hugo.pro/projects/godot-builds/), which is maintained by one of the Godot developers) and using that to open the project.

If you *really* want to try and use the project in Godot 3.0, see some of the later comments in #11 for details on what you need to change in the project.godot file to open the project. The biggest issue with opening the Godot 3.1 project in Godot 3 is all of the Input mappings are lost, so you’ll have to manually input them all in again if you want to use the project in Godot 3.

You may be able to download the project from the documentation and from Github, and replace the Github project.godot file with the documentation’s project.godot file. Then it may open in Godot 3.0 without needing the inputs remapped, but I have never done it so I cannot say whether it will work or not.

Hopefully this helps!

**Comment by ghost** [comment]
Thanks a lot! And thanks for replying so quickly! Will definitely try Godot 3.1 with the nightly builds.

Helped a lot!

**Comment by ghost** [comment]
@TwistedTwigleg it works :)

It just runs a bit slow, probably because my computer is trash, but it looks beautiful. I couldn't figure out how to make the guns visible and shootable. Is it supposed to be like that?

TIA,
Zeph

**Comment by TwistedTwigleg** [comment]
> @TwistedTwigleg it works :)

Great!

> It just runs a bit slow, probably because my computer is trash, but it looks beautiful. I couldn't figure out how to make the guns visible and shootable. Is it supposed to be like that?

You should be able to change the equipped weapon by pressing the 1-4 keys, scrolling with the mouse wheel, and/or by pressing left or right on a Xbox 360 controller.

I have not tried the project with the latest builds of Godot 3.1, so it's possible something changed and the project is broken (again). Let me know if you are still not able to change weapons and I'll see if I can fix it.

Hope this helps!

**Comment by ghost** [comment]
It works! It's just a little sluggish, may just be my computer though. At least it plays like it's supposed to!

Thanks a lot,
Zeph

**Comment by TwistedTwigleg** [comment]
Great! I’m glad everything works!

The project is a little more performance hungry than it should be and I’m not totally sure why. My hunch is it’s due to the Gridmap node, since performance was decent when the levels were just a bunch of nodes. Using the Gridmap node is much better for usability though, so I suppose for now it’s a trade off.

Hopefully in future versions of Godot the performance will get better!
Regardless, I’m glad it’s working! Closing this issue since everything worked out 👍

**Comment by ghost** [comment]
Yep, awesome. Thanks.
